CREATE DATABASE IF NOT EXISTS closetx;
USE closetx;
DROP TABLE IF EXISTS apparel;
DROP TABLE IF EXISTS user;
DROP USER IF EXISTS closetx;

CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NULL UNIQUE,
    email VARCHAR(100) NULL,
    password VARCHAR(255) NULL
);

CREATE TABLE apparel (
	id INT AUTO_INCREMENT PRIMARY KEY,
    user INT,
	uri VARCHAR(255),
	FOREIGN KEY (user) REFERENCES user(id),
    type INT
);

CREATE USER 'closetx'@'%' IDENTIFIED BY 'hello';
GRANT ALL PRIVILEGES ON *.* TO 'closetx'@'%';
FLUSH PRIVILEGES;