on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "INSTALLING DEPENDENCIES"
          pip3 install -r requirements.txt

  confirm:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Confirm test completion
        run: echo "Tests completed successfully"