on:
  pull_request:
    branches:
      - staging

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run pytest
        run: python3 -m pytest -v

  # build_images:
  #   runs-on: ubuntu-latest
  #   needs: unit_test
  #   steps:
  #     - name: Confirm test completion
  #       run: echo "All tests passed. Building and pushing app images"
  #     - name: build docker image