name: CI

on:
  pull_request:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "INSTALLING DEPENDENCIES" && pip3 install -r requirements.txt
      - name: Run tests
        run: cd test && python3 -m pytest -v
