on:
  pull_request:
    branches:
      - staging

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install pytest
        run: pip3 install -r requirements.txt
      - name: Run pytest
        run: python3 -m pytest -v

  build_images:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - name: Confirm test completion
        run: echo "All tests passed. Building and pushing app images"
      - name: pytest once more
        run: pip3 install -r requirements.txt